project_identifier: QKSMS
api_key: 6303f974868e96bd9aa7413b2c053c8c
base_path: /QKSMS/src/main/res
base_url: https://api.crowdin.com
preserve_hierarchy: true

files:
  -r
    source:      '/values/strings.xml'
    translation: '/values-%android_code%/%original_file_name%'
    languages_mapping:
      android_code:
        #Crowdin language code: your code
        bs-rBA : bs #Bosnian
        cs-rCZ : cs #Czech
        da-rDK : da #Danish
        de-rDE : de #German
        el-rGR : el #Greek
        es-rES : es #Spanish
        fi-rFI : fi #Finnish
        fr-rFR : fr #French
        hi-rIN : hi #Hindi
        hr-rHR : hr
        in-rID : in
        it-rIT : it #Italian
        iw-rIL : iw
        ko-rKR : ko #Korean
        lt-rLT : lt #Lithuanian
        ne-rNP : ne #Nepali
        nl-rNL : nl #Dutch
        no-rNO : no #Norweigan
        pl-rPL : pl #Polish
        pt-rBR : pt-rBR #Portuguese (brazil)
        pt-rPT : pt #Portuguese (portugal)
        ro-rRO : ro #Romanian
        ru-rRU : ru #Russian
        sk-rSK : sk #Slovak
        sv-rSE : sv #Swedish
        tl-rPH : tl #Tagalog
        tr-rTR : tr #Turkish
        zh-rCN : zh #Chinese (simplified)
        zh-rTW : zh-rTW #Chinese (traditional)
